name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build
      run: ./sportpaper build

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: sportpaper
        path: ./SportPaper-Server/target/sportpaper-1.8.8-R0.1-SNAPSHOT.jar
